trigger:
- "azure-kv-staticwebapp"

name: "StaticWebApp-ImageCarrier-UI"

variables:
  AzureSubscription: 'photon-dev-ai-cr'
  ArtifactName: 'ImageCarrierUI'
  BuildNumber: 'imagecarrier-ui-$(Build.BuildId).zip'
  TerraformBackendServiceConnection: 'terraform-service-principle'

stages:
  - stage: Build
    displayName: 'Build'
    variables:
      - group: 'dev-azure-imgcarrier-variable-group'
    jobs:
    - template: buildTemplate.yaml
      parameters:          
        environment: 'dev'
        ArtifactName:  '$(ArtifactName)'
        BuildNumber:  '$(BuildNumber)'
        TerraformBackendServiceConnection: '$(TerraformBackendServiceConnection)'

  - stage: Deploy_Dev
    displayName: 'Deploy to Dev'
    condition: succeeded('Build')
    dependsOn: Build
    variables:
      - group: 'dev-azure-imgcarrier-variable-group'
    jobs:
      - template: staticwebapp-deploymentTemplate.yaml
        parameters:
          environment: 'dev'
          ArtifactName:  '$(ArtifactName)'
          AzureSubscription:  '$(AzureSubscription)'
          BuildNumber:  '$(BuildNumber)'