trigger:
  branches:
    include:
    - 'playwright-pipeline'
    exclude:
    - '*'

name: "Playwright"

variables:
  AzureServiceConnName: "photon-dev-ai-cr"
  ArtifactName: "Playwright"
  DEV_BuildNumber: "Playwright-$(Build.BuildId).zip"

stages:
  - stage: Build_Dev
    displayName: "Build Dev"
    variables:
      - group: "dev-azure-imgcarrier-ui-static-variable-group"
    jobs:
      - template: buildTemplate.yaml
        parameters:
          environment: "dev"
          ArtifactName: "$(ArtifactName)"
          BuildNumber: "$(DEV_BuildNumber)"
          AzureServiceConnName: "$(AzureServiceConnName)"