trigger:
  branches:
    include:
    - 'master'
  tags:
    include:
    - 'refs/tags/release-imageCarrier-ui-v*'
  
  paths:
    include:
    - '/*'
    exclude:
    - 'pipelines/*'

# pr:
#   branches: 
#     include:
#     - 'master'
#     - 'release-imageCarrier-ui-v*'

name: "ImageCarrier-UI"

variables:
  AzureSubscription: 'photon-dev-ai-cr'
  ArtifactName: 'ImageCarrierUI'
  DEV_BuildNumber: 'imagecarrier-ui-dev-$(Build.BuildId).zip'
  QA_BuildNumber: 'imagecarrier-ui-qa-$(Build.BuildId).zip'
  STAGE_BuildNumber: 'imagecarrier-ui-stage-$(Build.BuildId).zip'
  PROD_BuildNumber: 'imagecarrier-ui-prod-$(Build.BuildId).zip'

stages:
  - stage: Build_Dev
    displayName: 'Build Dev'
    variables:
      - group: 'dev-azure-imgcarrier-ui-static-variable-group'
    jobs:
    - template: buildTemplate.yaml
      parameters:          
        environment: 'dev'
        ArtifactName:  '$(ArtifactName)'
        BuildNumber:  '$(DEV_BuildNumber)'

  - stage: Deploy_Dev
    displayName: 'Deploy to Dev'
    condition: succeeded('Build_Dev')
    dependsOn: Build_Dev
    variables:
      - group: 'dev-azure-imgcarrier-ui-static-variable-group'
    jobs:
      - template: deploymentTemplate.yaml
        parameters:
          environment: 'dev'
          ArtifactName:  '$(ArtifactName)'
          AzureSubscription:  '$(AzureSubscription)'
          BuildNumber:  '$(DEV_BuildNumber)'

  - stage: Build_QA
    displayName: 'Build QA'
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    dependsOn:
    - Build_Dev
    - Deploy_Dev
    variables:
      - group: 'qa-azure-imgcarrier-ui-static-variable-group'
    jobs:
    - template: buildTemplate.yaml
      parameters:          
        environment: 'qa'
        ArtifactName:  '$(ArtifactName)'
        BuildNumber:  '$(QA_BuildNumber)'

  - stage: Deploy_QA
    displayName: 'Deploy to QA'
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    dependsOn:
    - Build_Dev
    - Deploy_Dev
    - Build_QA
    variables:
      - group: 'qa-azure-imgcarrier-ui-static-variable-group'
    jobs:
      - template: deploymentTemplate.yaml
        parameters:
          environment: 'qa'
          ArtifactName:  '$(ArtifactName)'
          AzureSubscription:  '$(AzureSubscription)'
          BuildNumber:  '$(QA_BuildNumber)'

  - stage: Build_STAGING
    displayName: 'Build STAGING'
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    dependsOn:
    - Build_Dev
    - Deploy_Dev
    - Build_QA
    - Deploy_QA
    variables:
      - group: 'stage-azure-imgcarrier-ui-static-variable-group'
    jobs:
    - template: buildTemplate.yaml
      parameters:          
        environment: 'stage'
        ArtifactName:  '$(ArtifactName)'
        BuildNumber:  '$(STAGE_BuildNumber)'

  - stage: Deploy_QA
    displayName: 'Deploy to STAGING'
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    dependsOn:
    - Build_Dev
    - Deploy_Dev
    - Build_QA
    - Deploy_QA
    - Build_STAGING
    variables:
      - group: 'stage-azure-imgcarrier-ui-static-variable-group'
    jobs:
      - template: deploymentTemplate.yaml
        parameters:
          environment: 'stage'
          ArtifactName:  '$(ArtifactName)'
          AzureSubscription:  '$(AzureSubscription)'
          BuildNumber:  '$(STAGE_BuildNumber)'