# trigger:
#   branches:
#     include:
#     - 'master'
#     - 'release-imageCarrier-ui-v*'
#   tags:
#     include:
#     - 'release-imageCarrier-ui-v*'

# pr:
#   branches: 
#     include:
#       - 'master'
#       - 'release-imageCarrier-ui-v*'

trigger:
  branches:
    exclude:
      - '*'
  tags:
    include:
    - 'release-imageCarrier-ui-v*'
    # exclude:
    # - v2.0

pr:
  branches:
    include:
      - 'refs/tags/release-imageCarrier-ui-v*'
    exclude:
      # - 'refs/tags/v2.0'
      - '*'



name: "ImageCarrier-UI"

variables:
  AzureSubscription: 'photon-dev-ai-cr'
  ArtifactName: 'ImageCarrierUI'
  BuildNumber: 'imagecarrier-ui-$(Build.BuildId).zip'

stages:
- ${{ if ne(variables['Build.SourceBranch'], 'refs/tags/release-imageCarrier-ui-v') }}:
  - stage: Build_Dev
    displayName: 'Build Dev'
    variables:
      - group: 'dev-azure-imgcarrier-variable-group'
      - group: 'dev-azure-imgcarrier-ui-static-variable-group'
    jobs:
    - template: buildTemplate.yaml
      parameters:          
        environment: 'dev'
        ArtifactName:  '$(ArtifactName)'
        BuildNumber:  '$(BuildNumber)'

- ${{ if ne(variables['Build.SourceBranch'], 'refs/tags/release-imageCarrier-ui-v') }}:
  - stage: Deploy_Dev
    displayName: 'Deploy to Dev'
    condition: succeeded('Build_Dev')
    dependsOn: Build_Dev
    variables:
      - group: 'dev-azure-imgcarrier-variable-group'
      - group: 'dev-azure-imgcarrier-ui-static-variable-group'
    jobs:
      - template: deploymentTemplate.yaml
        parameters:
          environment: 'dev'
          ArtifactName:  '$(ArtifactName)'
          AzureSubscription:  '$(AzureSubscription)'
          BuildNumber:  '$(BuildNumber)'

- ${{ if eq(variables['Build.SourceBranch'], 'refs/tags/release-imageCarrier-ui-v') }}:
  - stage: Build_QA
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    dependsOn:
    - Build_Dev
    - Deploy_Dev
    variables:
      - group: 'qa-azure-imgcarrier-variable-group'
      - group: 'qa-azure-imgcarrier-ui-static-variable-group'
    jobs:
    - template: buildTemplate.yaml
      parameters:          
        environment: 'qa'
        ArtifactName:  '$(ArtifactName)'
        BuildNumber:  '$(BuildNumber)'

- ${{ if eq(variables['Build.SourceBranch'], 'refs/tags/release-imageCarrier-ui-v') }}:
  - stage: Deploy_QA
    displayName: 'Deploy to QA'
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    dependsOn:
    - Build_Dev
    - Deploy_Dev
    - Build_QA
    variables:
      - group: 'qa-azure-imgcarrier-variable-group'
      - group: 'qa-azure-imgcarrier-ui-static-variable-group'
    jobs:
      - template: deploymentTemplate.yaml
        parameters:
          environment: 'qa'
          ArtifactName:  '$(ArtifactName)'
          AzureSubscription:  '$(AzureSubscription)'
          BuildNumber:  '$(BuildNumber)'