trigger:
  branches:
    include:
    - 'playwright-pipeline'

name: "Playwright"

variables:
  AzureServiceConnName: "photon-dev-ai-cr"
  ArtifactName: "ImageCarrierUI"
  DEV_BuildNumber: "imagecarrier-ui-dev-$(Build.BuildId).zip"
  QA_BuildNumber: "imagecarrier-ui-qa-$(Build.BuildId).zip"
  # STAGE_BuildNumber: "imagecarrier-ui-stage-$(Build.BuildId).zip"
  PROD_BuildNumber: "imagecarrier-ui-prod-$(Build.BuildId).zip"

stages:
  - stage: Build_Dev
    displayName: "Build Dev"
    variables:
      - group: "dev-azure-imgcarrier-ui-static-variable-group"
    jobs:
      - template: buildTemplate.yaml
        parameters:
          environment: "dev"
          ArtifactName: "$(ArtifactName)"
          BuildNumber: "$(DEV_BuildNumber)"
          AzureServiceConnName: "$(AzureServiceConnName)"

  - stage: Deploy_Dev
    displayName: "Deploy to Dev"
    condition: |
      and(
        succeeded('Build_DEV'),
        ne(variables['Build.Reason'], 'PullRequest'),
        startsWith(variables['Build.SourceBranch'], 'refs/heads/master')
      )
    dependsOn: Build_Dev
    variables:
      - group: "dev-azure-imgcarrier-ui-static-variable-group"
    jobs:
      - template: deploymentTemplate.yaml
        parameters:
          environment: "dev"
          ArtifactName: "$(ArtifactName)"
          AzureServiceConnName: "$(AzureServiceConnName)"
          BuildNumber: "$(DEV_BuildNumber)"

  - stage: Build_QA
    displayName: "Build QA"
    condition: |
      and(
        ne(variables['Build.Reason'], 'PullRequest'),
        startsWith(variables['Build.SourceBranch'], 'refs/heads/release/MVP-v')
      )
    variables:
      - group: "qa-azure-imgcarrier-ui-static-variable-group"
    jobs:
      - template: buildTemplate.yaml
        parameters:
          environment: "qa"
          ArtifactName: "$(ArtifactName)"
          BuildNumber: "$(QA_BuildNumber)"
          AzureServiceConnName: "$(AzureServiceConnName)"

  - stage: Deploy_QA
    displayName: "Deploy to QA"
    condition: |
      and(
        succeeded('Build_QA'),
        ne(variables['Build.Reason'], 'PullRequest'),
        startsWith(variables['Build.SourceBranch'], 'refs/heads/release/MVP-v')
      )
    dependsOn:
      - Build_QA
    variables:
      - group: "qa-azure-imgcarrier-ui-static-variable-group"
    jobs:
      - template: deploymentTemplate.yaml
        parameters:
          environment: "qa"
          ArtifactName: "$(ArtifactName)"
          AzureServiceConnName: "$(AzureServiceConnName)"
          BuildNumber: "$(QA_BuildNumber)"

  # - stage: Build_STAGING
  #   displayName: "Build STAGING"
  #   condition: |
  #     and(
  #       succeeded('Deploy_QA'),
  #       ne(variables['Build.Reason'], 'PullRequest'),
  #       startsWith(variables['Build.SourceBranch'], 'refs/heads/release/MVP-v')
  #     )
  #   dependsOn:
  #     - Build_QA
  #     - Deploy_QA
  #   variables:
  #     - group: "stage-azure-imgcarrier-ui-static-variable-group"
  #   jobs:
  #     - template: buildTemplate.yaml
  #       parameters:
  #         environment: "stage"
  #         ArtifactName: "$(ArtifactName)"
  #         BuildNumber: "$(STAGE_BuildNumber)"
  #         AzureServiceConnName: "$(AzureServiceConnName)"

  # - stage: Deploy_STAGING
  #   displayName: "Deploy to STAGING"
  #   condition: |
  #     and(
  #       succeeded('Build_STAGING'),
  #       ne(variables['Build.Reason'], 'PullRequest'),
  #       startsWith(variables['Build.SourceBranch'], 'refs/heads/release/MVP-v')
  #     )
  #   dependsOn:
  #     - Build_QA
  #     - Deploy_QA
  #     - Build_STAGING
  #   variables:
  #     - group: "stage-azure-imgcarrier-ui-static-variable-group"
  #   jobs:
  #     - template: deploymentTemplate.yaml
  #       parameters:
  #         environment: "stage"
  #         ArtifactName: "$(ArtifactName)"
  #         AzureServiceConnName: "$(AzureServiceConnName)"
  #         BuildNumber: "$(STAGE_BuildNumber)"

  - stage: Build_PROD
    displayName: 'Build PROD'
    condition: |
      and(
        succeeded('Deploy_QA'),
        ne(variables['Build.Reason'], 'PullRequest'),
        startsWith(variables['Build.SourceBranch'], 'refs/heads/release/MVP-v')
      )
    dependsOn: 
    - Build_QA
    - Deploy_QA
    # - Build_STAGING
    # - Deploy_STAGING
    variables:
      - group: 'prod-azure-imgcarrier-ui-static-variable-group'
    jobs:
    - template: buildTemplate.yaml
      parameters:          
        environment: 'prod'
        ArtifactName:  '$(ArtifactName)'
        AzureServiceConnName:  '$(AzureServiceConnName_PROD)'
        BuildNumber:  '$(PROD_BuildNumber)'

  - stage: Deploy_PROD
    displayName: "Deploy to PROD"
    condition: |
      and(
        succeeded('Build_PROD'),
        ne(variables['Build.Reason'], 'PullRequest'),
        startsWith(variables['Build.SourceBranch'], 'refs/heads/release/MVP-v')
      )
    dependsOn:
      - Build_QA
      - Deploy_QA
      # - Build_STAGING
      # - Deploy_STAGING
      - Build_PROD
    variables:
      - group: "prod-azure-imgcarrier-ui-static-variable-group"
    jobs:
      - template: deploymentTemplate.yaml
        parameters:
          environment: "prod"
          ArtifactName: "$(ArtifactName)"
          AzureServiceConnName: "$(AzureServiceConnName_PROD)"
          BuildNumber: "$(PROD_BuildNumber)"
