parameters:  
  - name: environment
  - name: ArtifactName
  - name: AzureSubscription

jobs:
  - deployment:
    displayName: '${{ parameters.environment }}'
    environment: '${{ parameters.environment }}'
    pool:
      vmImage: "ubuntu-20.04"
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
              submodules: true
            - task: DownloadBuildArtifacts@1
              displayName: 'Download latest build artifact'
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: '${{ parameters.ArtifactName }}'
                downloadPath: '$(System.DefaultWorkingDirectory)/${{ parameters.environment }}'

            - task: ExtractFiles@1
              inputs:
                archiveFilePatterns: '**/imagecarrier-ui.zip'
                destinationFolder: '$(System.DefaultWorkingDirectory)/${{ parameters.environment }}/apps/'
                cleanDestinationFolder: true
                overwriteExistingFiles: true

            - task: AzureStaticWebApp@0
              inputs:
                cwd: '$(System.DefaultWorkingDirectory)/${{ parameters.environment }}/apps/'
                app_location: '/'
                output_location: 'wwwroot'
                config_file_location: '/dist'
                skip_app_build: true
                skip_api_build: true
                is_static_export: false
                verbose: true
              env:
                azure_static_web_apps_api_token: $(StaticWebAppToken)